# Generated by Django 4.1 on 2022-10-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('mini_descripcion', models.CharField(max_length=60, null=b'I01\n')),
                ('descripcion', models.TextField(null=b'I01\n')),
                ('ruta_img', models.CharField(max_length=255, null=b'I01\n')),
                ('categoria', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True, null=b'I01\n')),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
