# Generated by Django 4.1 on 2022-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_img', models.CharField(max_length=255, null=b'I01\n')),
                ('id_publicacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_descripcion', models.CharField(max_length=60, null=b'I01\n')),
                ('descripcion', models.TextField(null=b'I01\n')),
                ('categoria', models.CharField(max_length=50)),
                ('codigo_producto', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('status', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True, null=b'I01\n')),
                ('id_vendedor', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
