# Generated by Django 4.1 on 2022-10-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_imagenes_publicaciones_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='id_imagenes',
            field=models.IntegerField(null=b'I01\n', unique=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='id_publicacion',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='id_publicacion',
            field=models.IntegerField(null=b'I01\n'),
        ),
    ]
