# Generated by Django 4.1 on 2022-10-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_imagenes_id_imagenes_publicaciones_id_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='ruta_img',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(null=b'I01\n', upload_to='static/img/productos'),
            preserve_default=b'I01\n',
        ),
    ]
