# Generated by Django 4.1.2 on 2022-10-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_imagenes_ruta_img_imagenes_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='ruta_img',
            field=models.CharField(max_length=255, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
