# Generated by Django 4.1 on 2022-10-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id_publicaciones', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('resumen', models.CharField(max_length=100, null=b'I01\n')),
                ('contenido', models.CharField(max_length=255, null=b'I01\n')),
                ('id_categoria', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True, null=b'I01\n')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
            ],
        ),
    ]
