# Generated by Django 4.1 on 2022-10-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
